### ISSUE TITLE
some documentation?

### ISSUE THREAD

**Issue by alberto-bottarini** [cartertinney/7wonders#1]
I really like your project (i was thinking about a nodejs version).
What do you think about a complete documentation?

**Comment by cartertinney** [comment]
To be honest, I'd like to, but I actually don't remember how it all 
works. It was never documented for public use because it doesn't 
actually quite work. 99% of the game does, but one of the boards 
(Ephesos B as I recall) doesn't have the functionality for it's third 
stage wonder implemented. I always meant to finish it but never quite 
got around to it.

The codebase itself is also kind of poor (although it is functional, 
except for that one specific wonder). But if you're still interested in 
using it, I could see what I can do about coming up with some kind of 
documentation.

**Comment by alberto-bottarini** [comment]
Thanks for reply!
I found your project using google and I would like to use it as inspiration :)
So don't worry about documentation. I'll use only the code.

Thanks again
